version: 2
jobs:
  build:
    docker:
      - image: ansible/centos7-ansible
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, word!!!
      - run:
          name: Print The Current time
        command: date
      - run:
      	  name: Ansible ping
      	  command: ansible-playbook ping.yml
      	  