version: 2
jobs:
  build:
    working_directory: ~/rpmbuild
    context: Docker
    docker:
      - image: centos
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Install packages
            command: yum -y install epel-release && yum -y install rpm-build rpmdevtools git jq libtool-ltdl awscli
        - run:
            name: Create rpmbuild tree
            command: rpmdev-setuptree && mkdir ~/rpmbuild/RPMS/noarch
        - run:
            name: Show list
            command: ls -l ~/rpmbuild/RPMS
        - run:
            name: Download container
            command: |
                docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASS}
                docker pull mobichord/integration-tem-sftp:1.2.1
                docker images

workflows:
  version: 2
  build:
    jobs:
      - build
