version: 2
jobs:
  build:
    working_directory: ~/rpmbuild
    docker:
      - image: centos
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Install packages
            command: yum -y install epel-release && yum -y install rpm-build rpmdevtools git jq libtool-ltdl awscli
        - run:
            name: Create rpmbuild tree
            command: rpmdev-setuptree && mkdir ~/rpmbuild/RPMS/noarch
        - run:
            name: Show list
            command: ls -l ~/rpmbuild/RPMS
        - run:
            name: Install docker
            command: |
              set -x
              VER="18.06.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f  /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin/
              
        - run:
            name: Download container
            command: |
                IMAGES="integration-tem-sftp:1.2.1"
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker pull mobichord/${IMAGES}
                docker images
                docker save -o ${IMAGES}.tar mobichord/${IMAGES}
                ls -l  ${IMAGES}.tar

workflows:
  version: 2
  build:
    jobs:
      - build
