version: 2
jobs:
  build:
    docker:
      - image: centos
    steps:
        - checkout
        - run:
            name: Install packages
            command: yum -y install epel-release && yum -y install rpm-build rpmdevtools git jq libtool-ltdl awscli
        - run:
            name: Create rpmbuild tree
            command: rpmdev-setuptree && mkdir ~/rpmbuild/RPMS/noarch
        - run:
            name: Show list
            command: ls -l ~/rpmbuild/RPMS

workflows:
  version: 2
  build:
    jobs:
      - build
