version: 2
jobs:
  build:
    working_directory: ~/opt/rpmbuild
    docker:
      - image: centos
    steps:
        - checkout
        - setup_remote_docker
        - persist_to_workspace:
            root: .
            paths:
                - .
       - run:
          name: install package
          command: yum -y install epel-release && yum -y install rpm-build rpmdevtools git jq libtool-ltdl 
      
      - run:
          name: Create rpmbuild tree
          command: |
            rpmdev-setuptree 
            mkdir ~/rpmbuild/RPMS/noarch
        
        - run:
            name: Install docker
            command: |
              set -x
              VER="18.06.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f  /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin/
              
        - run:
            name: Download container
            command: |
                IMAGES="jenkins:latest"
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker pull andrewpgit/${IMAGES}
                docker images
                docker save -o ${IMAGES}.tar andrewpgit/${IMAGES}
                ls -l  ${IMAGES}.tar
  deploy:
    working_directory: ~/opt/rpmbuild
    docker:
      - image: centos
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Intall packages
          command: yum install epel-release && yum install awscli
          
      - run:
          name: List
          command: ls -l  
          
      
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
