version: 2
jobs:
  build:
    working_directory: /opt/rpmbuild
    docker:
      - image: centos
    steps:
        - checkout
        - setup_remote_docker
        - persist_to_workspace:
            root: /opt/rpmbuild
            paths:
                - dist
        - run:
            name: install package
            command: yum -y install epel-release && yum -y install git jq libtool-ltdl
        
        - run:
           name: Install docker
           command: |
              set -x
              VER="18.06.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f  /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin/
        
        - run:
           name: Download container
           command: |
                IMAGES="jenkins:latest"
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                cd dist && mkdir images
                cd images && docker pull andrewpgit/${IMAGES}
                docker images
                docker save -o ${IMAGES}.tar andrewpgit/${IMAGES}
                ls -l  ${IMAGES}.tar
  deploy:
    working_directory: /opt/rpmbuild
    docker:
      - image: centos
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /opt/rpmbuild
          
      - run:
          name: Intall packages
          command: yum -y install epel-release && yum -y install awscli rpm-build rpmdevtools
  
      - run:
          name: Create rpmbuild tree
          command: |
              rpmdev-setuptree 
              mkdir ~/rpmbuild/RPMS/noarch

      - run:
          name: List
          command: |  
            ls -l  dist/
            ls -l  dist/images
            ls -l ~/rpmbuild/RPMS/noarch
      
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
